[什么是脚本错误](https://blog.sentry.io/2016/05/17/what-is-script-error)

# 什么是脚本错误

如果您以前使用过JavaScript onerror事件做过任何工作，您可能会遇到以下情况：

"Script error."

“脚本错误”是当错误源自从不同来源（不同域，端口或协议）提供的JavaScript文件时，浏览器发送到onerror回调的内容。这很痛苦，因为即使出现错误，您也不知道错误是什么，也不知道它来自哪个代码。这就是window.onerror的全部目的 - 深入了解应用程序中未捕获的错误。

## 原因：跨源脚本

为了更好地了解正在发生的事情，请考虑以下示例HTML文档，假设从http://example.com/test提供：

```html
<!doctype html>
<html>
<head>
  <title>example.com/test</title>
</head>
<body>
  <script src="http://another-domain.com/app.js"></script>
  <script>
    window.onerror = function (message, url, line, column, error) {
      console.log(message, url, line, column, error);
    }
    foo(); // call function declared in app.js
  </script>
</body>
</html>
```

这是http://another-domain.com/app.js的内容。它声明了一个函数foo，其调用将始终抛出ReferenceError。

在浏览器中加载此文档并执行JavaScript时，会将以下内容输出到控制台（通过window.onerror回调记录）：

"Script error.", "", 0, 0, undefined

这不是JavaScript错误 - 出于安全原因，浏览器故意隐藏源自不同来源的脚本文件的错误。这是为了避免脚本无意中将潜在敏感信息泄露给它无法控制的onerror回调。出于这个原因，浏览器只允许window.onerror洞察来自同一域的错误。我们所知道的是发生了一个错误 - 没有别的！

## 但这并不坏

尽管浏览器有良好的意图，但是有一些很好的理由可以让您深入了解从不同来源提供的脚本引发的错误：

1. 您的应用程序JavaScript文件是从不同的主机名提供的，例如static.sentry.io/app.js
2. 您正在使用社区CDN提供的库，例如cdnjs或Google的托管库
3. 您正在使用商业第三方JavaScript库，该库仅由外部服务器提供

但不要担心 - 深入了解这些文件所提供的JavaScript错误只需要进行一些简单的调整。

## 修复：CORS attributes & headers

为了了解源自不同来源的脚本引发的JavaScript异常，您必须做两件事:

1. 添加 crossorigin="anonymous" 脚本属性

`<script src="http://another-domain.com/app.js" crossorigin="anonymous"></script>`

这告诉浏览器应该“anonymous”(匿名)获取目标文件。这意味着在请求此文件时，浏览器不会将任何潜在的用户识别信息（如cookie或HTTP凭据）传输到服务器。

2. 添加Cross Origin HTTP header

`Access-Control-Allow-Origin: *`

CORS是“跨源资源共享”的缩写，它是一组API（主要是HTTP标头），它们规定了文件应该如何从源头下载和提供。

通过设置Access-Control-Allow-Origin：*，服务器向浏览器指示任何源可以获取此文件。或者，您可以将其限制为您控制的已知来源，例如

`Access-Control-Allow-Origin: https://www.example.com`

注意：大多数社区CDN正确设置了Access-Control-Allow-Origin标头。

```bash
$ curl --head https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.js | \
  grep -i "access-control-allow-origin"

Access-Control-Allow-Origin: *
```

完成这两个步骤后，此脚本触发的任何错误都将向window.onerror报告，就像任何常规的同域脚本一样。因此，代替“脚本错误”，从一开始的onerror示例将产生：

`"ReferenceError: bar is not defined", "http://another-domain.com/app.js", 2, 1, [Object Error]`

## 另一种解决方案：try / catch

有时，我们并不总是能够调整Web应用程序正在使用的脚本的HTTP头。在这些情况下，有一种替代方法：使用try / catch。

再次考虑原始示例，这次使用try / catch：

```html
<!-- note: crossorigin="anonymous" intentionally absent -->
<script src="http://another-domain.com/app.js"></script>
<script>
  window.onerror = function (message, url, line, column, error) {
    console.log(message, url, line, column, error);
  }

  try {
    foo(); // call function declared in app.js
  } catch (e) {
    console.log(e);
    throw e; // intentionally re-throw (caught by window.onerror)
  }
</script>
```

对于后代，some-domain.com/app.js再次看起来像这样：

```js
// another-domain.com/app.js
function foo() {
  bar(); // ReferenceError: bar is not a function
}
```

运行示例HTML将向控制台输出以下2个条目：

```bash
=> ReferenceError: bar is not defined
    at foo (http://another-domain.com/b.js:2:3)
    at http://example.com/test/:15:3

=> "Script error.", "", 0, 0, undefined
```

第一个控制台语句 - 来自try / catch - 设法获取一个错误对象，包括类型，消息和堆栈跟踪，包括文件名和行号。来自window.onerror的第二个控制台语句再一次只能输出“脚本错误”。

现在，这是否意味着您需要尝试/捕获所有代码？可能不是 - 如果您可以轻松更改HTML并在CDN上指定CORS标题，则最好这样做并坚持使用window.onerror。但是，如果您不控制这些资源，使用try / catch包装第三方代码是一种可靠的（虽然是乏味的）方式，可以深入了解跨源脚本引发的错误。

注意：默认情况下，Raven.js - Sentry的JavaScript SDK - 仔细设备内置方法，尝试自动将代码包装在try / catch块中。它这样做是为了尝试捕获所有脚本中的错误消息和堆栈跟踪，无论它们来自哪个来源。如果可能，仍建议设置CORS属性和标头。

如果这篇博客文章帮助你，并且你想了解更多关于window.onerror的信息，你还应该查看我们的其他博客文章：使用window.onerror捕获并报告JavaScript错误 [Capture and report JavaScript errors with window.onerror](https://blog.sentry.io/2016/01/04/client-javascript-reporting-window-onerror.html)
